// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9q5rDZpGNYIxnQJd7_ggeOopR4xg5Y-M',
    appId: '1:1094366113062:web:9b0751f33bd862517065e7',
    messagingSenderId: '1094366113062',
    projectId: 'fixmatecustomer',
    authDomain: 'fixmatecustomer.firebaseapp.com',
    storageBucket: 'fixmatecustomer.firebasestorage.app',
    measurementId: 'G-TKT98RS8SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYJqksShL5jwKplucCr2LtEDbktpR_QK8',
    appId: '1:1094366113062:android:9099094a881a400e7065e7',
    messagingSenderId: '1094366113062',
    projectId: 'fixmatecustomer',
    storageBucket: 'fixmatecustomer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGuT1o2-OX1n3BKCN7QRJ7xFgr5oiTRA',
    appId: '1:1094366113062:ios:20c422b7f2492f4d7065e7',
    messagingSenderId: '1094366113062',
    projectId: 'fixmatecustomer',
    storageBucket: 'fixmatecustomer.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQGuT1o2-OX1n3BKCN7QRJ7xFgr5oiTRA',
    appId: '1:1094366113062:ios:20c422b7f2492f4d7065e7',
    messagingSenderId: '1094366113062',
    projectId: 'fixmatecustomer',
    storageBucket: 'fixmatecustomer.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9q5rDZpGNYIxnQJd7_ggeOopR4xg5Y-M',
    appId: '1:1094366113062:web:2c3da346d1319cfe7065e7',
    messagingSenderId: '1094366113062',
    projectId: 'fixmatecustomer',
    authDomain: 'fixmatecustomer.firebaseapp.com',
    storageBucket: 'fixmatecustomer.firebasestorage.app',
    measurementId: 'G-2G6SXLXHJ3',
  );
}
